name: Unit tests

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        php: ['8.2', '8.3']
        typo3: ['^13.4']
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}, TYPO3 ${{ matrix.typo3 }}
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Declare required TYPO3 version
      run: |
        composer require --no-update --dev typo3/cms-core ${{ matrix.typo3 }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      run: .Build/bin/phpunit --colors -c Tests/Build/UnitTests.xml

    - name: Run PHP lint
      run: find . -name \*.php ! -path "./.Build/*" ! -path "./public/*" ! -path "./vendor/*" | xargs -n1 php -d display_errors=stderr -l

    - name: Validate PHP coding guidelines
      run: |
        .Build/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -v --dry-run --stop-on-violation --using-cache=no